name: RESTAPI-CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.303"

      - name: Restore dependencies
        run: dotnet restore ./HR.LeaveManagmant.Clean.sln

      - name: Build
        run: dotnet build ./HR.LeaveManagmant.Clean.sln

      - name: Test
        run: dotnet test ./HR.LeaveManagmant.Clean.sln

      - name: Clean up previous publish artifacts
        run: rm -rf ./publish

      - name: Publish Artifact
        run: dotnet publish ./HR.LeaveManagmant.Clean.sln -c Release -o ./publish

      - name: Archive Published Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: publish
          path: ./publish

     